### ISSUE TITLE
Shakemap output has only longitudes

### ISSUE THREAD

**Issue by bpross-52n** [GFZ-Centre-for-Early-Warning/shakyground#1]
In the following line:

https://github.com/GFZ-Centre-for-Early-Warning/shakyground/blob/48775d7dbc7e1dcf4c3c49603de43b5928f04393/service.py#L139

sm["LAT"] = sites["lon"]

should be replaced by

sm["LAT"] = sites["lat"]

**Comment by maxpittore** [comment]
thanks. committed the fix
